name: eth_abi_codec
description: decode and encode for eth contract call
version: 2.0.0
homepage: https://github.com/nbltrust/dart-eth-abi-codec

dependencies:
  convert: ^3.1.0
  pointycastle: ^3.6.2
  typed_data: ^1.3.1

environment:
  sdk: ">=2.17.0 <3.0.0"
